services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: mcr.microsoft.com/devcontainers/javascript-node:18
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    - node_modules:/com.docker.devenvironments.code/node_modules
volumes:
  node_modules:
