services:
  app:
    entrypoint: ["entrypoint.sh"]
    image: mcr.microsoft.com/devcontainers/javascript-node:18
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
